# Generated by Django 4.0.5 on 2022-06-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Back_Load_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_load_material', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=250, null=True)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('tonn', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=250, null=True)),
                ('km', models.CharField(blank=True, max_length=250, null=True)),
                ('deisel', models.CharField(blank=True, max_length=250, null=True)),
                ('expense', models.CharField(blank=True, max_length=250, null=True)),
                ('back_load', models.BooleanField(default=False)),
                ('back_load_material', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='carriage_type',
            field=models.CharField(blank=True, choices=[('Clinker', 'Clinker'), ('Cement', 'Cement')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Income_Per_Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(blank=True, max_length=250, null=True)),
                ('earning', models.CharField(blank=True, max_length=250, null=True)),
                ('back_load', models.BooleanField(default=False)),
                ('tonn', models.CharField(blank=True, max_length=250, null=True)),
                ('back_load_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.back_load_material')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.add_vehicle')),
            ],
        ),
    ]
