# Generated by Django 4.0.5 on 2022-06-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_expense_route_deisel_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated_Deisel_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deisel_price', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='back_load_material',
            name='tonn',
        ),
        migrations.AddField(
            model_name='route',
            name='updated_deisel_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.updated_deisel_price'),
        ),
    ]
