# Generated by Django 4.0.5 on 2022-06-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_updated_deisel_price_remove_back_load_material_tonn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income_per_route',
            old_name='expense',
            new_name='total_expense',
        ),
        migrations.RemoveField(
            model_name='route',
            name='deisel',
        ),
        migrations.RemoveField(
            model_name='route',
            name='deisel_expense',
        ),
        migrations.RemoveField(
            model_name='route',
            name='updated_deisel_price',
        ),
        migrations.AddField(
            model_name='income_per_route',
            name='updated_deisel_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.updated_deisel_price'),
        ),
    ]
