# Generated by Django 4.0.5 on 2022-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_expense_income_per_route_total_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_per_route',
            name='deisel_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
