# Generated by Django 4.0.5 on 2022-06-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_add_vehicle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
