# Generated by Django 4.0.5 on 2022-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_add_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_image'),
        ),
    ]
