# Generated by Django 4.0.5 on 2022-06-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_otp',
        ),
    ]
